### ISSUE TITLE
Updatebeleid Baseline

### ISSUE THREAD

**Issue by jannickoeben** [SURFnet/Azure-NBA-Policy-template#3]
Goedemiddag,

Dank voor het maken van deze baseline! Wij hanteren deze als leidende baseline voor onze Azure omgeving, mede omdat het Surf normenkader/toetskader als leidend wordt gehanteerd door onze afdeling/organisatie.

In de readme wordt gesteld:
_Periodiek zal deze template worden geupdate met nieuwe policies en/of aanpassingen de focus ligt dan op deprecated policies en/of nieuwe policies die in de Microsoft Security Baseline zijn toegevoegd en ook van toepassing zijn op de SURFaudit controls. Zie hiervoor het update process._

Er is tot nu toe alleen een initiele versie neergezet ruim een jaar geleden, en dus nog geen update. Is er duidelijkheid over wie op welk termijn die periodieke update uitvoert? Is er bijvoorbeeld ook duidelijk wanneer het preview label er af gaat?
Daarnaast staat er een verwijzing naar 'het update process', kan iemand me vertellen waar die staat?

**Comment by JoostGadellaa** [comment]
Terechte vraag! Ik weet alleen dat ik er zelf niet meer bij betrokken ben. Ik zal er intern eens navraag over doen.

**Comment by JoostGadellaa** [comment]
We gaan binnenkort dit template archiveren en doorverwijzen naar de relevante BIO en ISO policy initiatives waar deze op gebaseerd zijn. Die templates hebben een actieve groep _contributers_, binnen SURF bleek daar niet genoeg animo voor.
